### PR TITLE
Added support for SVG

### PR DESCRIPTION
**Pull request by basvandijk**
Hi @asayers,

I added preliminary support for SVG to blaze-react. I haven't added documentation yet. 

For reference see: http://facebook.github.io/react/docs/tags-and-attributes.html#svg-elements

### CODE REVIEW

**Comment by meiersi** [comment]
Cool! Nice work. Thanks a lot!

**Comment by asayers** [comment]
Nice!

@basvandijk: I notice that the folloing will typecheck:

```haskell
myHtml :: Html
myHtml = do
    svg $ span "foo"                             -- HTML elements inside an SVG tag
    div $ circle ! cx "50" ! cy "50" ! r "40"    -- SVG elements outside an SVG tag
```

Does the SVG spec allow these cases? If not, do you think we should newtype `Svg`? It would mean adding a little unwrapping code to the renderers I guess.

@meiersi: Perhaps SVG support can be merged back into blaze-html?

**Comment by meiersi** [comment]
@asayers, one could consider merging it back. We'll have to make sure that it supports the full standard and not just the subset supported by ReactJS.

**Comment by basvandijk** [comment]
> Does the SVG spec allow these cases?

No it doesn't. SVG does have the [foreignObject](https://developer.mozilla.org/en/docs/Web/SVG/Element/foreignObject) element which allows embedding HTML but react doesn't seem to support it.

> If not, do you think we should newtype Svg? It would mean adding a little unwrapping code to the renderers I guess.

I think that makes sense. We do have to think about how to support attributes like `class_` and `id` which are supported by both HTML and SVG.

**Pull request merged**
